### ISSUE TITLE
Question - 

### ISSUE THREAD

**Issue by victorbjorklund** [utkuozdemir/helm-charts#2]
Hi! Awesome to see you put this together! Quick question (might be a bit stupid since I'm not very good with k8s, ruby or huginn) but if you want to add more agents than the default by for example creating your own (https://github.com/huginn/huginn_agent). Then I assume you could just create your own image including those gem:s and then reinstall the chart. Correct? Or is there a better way?

So change this: 

```
artifacthub.io/images: |
  - name: huginn/huginn
    image: docker.io/huginn/huginn-single-process:4d17829cf6b15b004ad3f4be196303dca4944810
```

To this: 

```
artifacthub.io/images: |
  - name: huginn/huginn
    image: docker.io/victorbjorklund/custom-huginn:latest
```

**Comment by utkuozdemir** [comment]
Hi Victor! Glad that you like the chart.

You got it almost right. You can pass a custom image, but not through`artifacthub.io/images` - this is just metadata for [ArtifactHub](https://artifacthub.io/packages/helm/utkuozdemir/huginn) so it can generate the image security rating etc.

To use a custom image, you don't need to change the chart at all - you simply pass a different image and tag through external values. See the default values file: https://github.com/utkuozdemir/helm-charts/blob/master/huginn/values.yaml#L5-L9

Basically, you need to do either:
```
helm install huginn utkuozdemir/huginn --set image.repository=docker.io/victorbjorklund/custom-huginn --set image.tag=latest`
```

or pass it via a custom values.yaml file
```
helm install huginn utkuozdemir/huginn --values custom-values.yaml
```
with `custom-values.yaml` content:
```yaml
image:
  repository: docker.io/victorbjorklund/custom-huginn
  tag: latest
```
Btw, you don't even to reinstall the chart - you can use `helm upgrade ...`
Also, make sure to base your image on `docker.io/huginn/huginn-single-process` image so it will be compatible with the chart.

**Comment by victorbjorklund** [comment]
Makes sense! Thanks!
