### ISSUE TITLE
Support Kubernetes 1.22 for ingress

### ISSUE THREAD

**Issue by unixfox** [utkuozdemir/helm-charts#7]
The ingress API version got changed in Kubernetes 1.22.

Thus, all the charts don't work on Kubernetes >= 1.22 when ingress is enabled.

**Comment by utkuozdemir** [comment]
Resolved in the commits:
https://github.com/utkuozdemir/helm-charts/commit/c4591ee7161e2a001d8f65d629bc531621bd4805
https://github.com/utkuozdemir/helm-charts/commit/8339261c3a9092874d3709c7eff0b736e8d26afe
https://github.com/utkuozdemir/helm-charts/commit/c5e88088e6cabc8b0886222abf2a663c0abc606e
